#!/bin/sh

# Location: /var/git/magnify/hooks/post-receive
# This script is run on the production server when the repo has been pushed
# to production. It checks out the repo files to a build directory where
# the frontend is built.

# Set production mode
NODE_ENV=production

# Location of git repo on server
GIT_REPO_DIR=/var/git/magnify

# Directories for git checkout and building
BUILD_DIR=/var/git/magnify-build
BUILD_FRONTEND_DIR=$BUILD_DIR/frontend
BUILD_BACKEND_DIR=$BUILD_DIR/backend

# Install directories for frontend and backend
INSTALL_FRONTEND_DIR=/var/www/magnify.today
INSTALL_BACKEND_DIR=/srv/magnify-api

# Checkout git files to build directory
if [ ! -d "$BUILD_DIR" ]; then
  mkdir $BUILD_DIR
fi

git --work-tree=$BUILD_DIR --git-dir=$GIT_REPO_DIR checkout -f

# Build and copy frontend files to web server directory
echo "*** Building frontend ***"
cd $BUILD_FRONTEND_DIR
yarn && yarn build
cp -R $BUILD_FRONTEND_DIR/build/* $INSTALL_FRONTEND_DIR

# Build and restart backend
echo "*** Building backend ***"
cp -R $BUILD_BACKEND_DIR/* $INSTALL_BACKEND_DIR
cd $INSTALL_BACKEND_DIR
yarn
sudo systemctl restart magnify
